### ISSUE TITLE
Resident Evil:Village hangs

### ISSUE THREAD

**Issue by Mike2003-1** [HansKristian-Work/vkd3d-proton#1357]
Hello, i recently posted some issues about my gameplay of RE:8 in r/Linux_Gaming. I managed to get some proton logs but was asked to post my issue here.

Basically, I noticed while playing the game that everything is fine until you get to an abandoned house outside the village. The game will hang after the furniture falls upstairs, and you go around the corner to see it.

Here is the original reddit post: [RE:8 hang issue on linux](https://www.reddit.com/r/linux_gaming/comments/znxeda/resident_evil_freezing_on_steam/)

I can get out of the game with Alt + Tab and get Steam to stop the game.

Using:
Manjaro Linux
NVidia GeForce RTX 3070 Ti
Proton 7.0-5 (Also errors on GE-Proton7-43, but below log is in 7.0-5)

Below is my log. Can someone guide me to figure out what is causing this issue? I am willing to get additional information with guidance.

I did play this game and it worked perfectly a few months ago, so the error should not be hardware related.

[steam-1196590.log](https://github.com/HansKristian-Work/vkd3d-proton/files/10317198/steam-1196590.log)

Thanks for the help!

Edit: Based on comments for this #1354 similar issue, i have gotten some logs with launch option set to "PROTON_LOG=1 VKD3D_DEBUG=warn %command%", hoping it helps shed more light. To be clear, I am using Native Steam, not Lutris.

[steam-1196590.log](https://github.com/HansKristian-Work/vkd3d-proton/files/10317235/steam-1196590.log)

Here are my currently installed NVidia Packages

![image](https://user-images.githubusercontent.com/121589492/209893426-b1faf606-ba3a-416b-a6a7-ac4c923f9e5d.png)

Again, thanks in advance for any help on this issue!

**Comment by RiantAnda** [comment]
Both your logs show:
`vkd3d_allocate_device_memory: Memory allocation failed, falling back to system memory.`
Maybe lowering your graphics settings could help?

I have the exact same issue, but for me it seems to be a driver issue. Syslog shows:
`NVRM: Xid (PCI:0000:01:00): 109, pid=15138, name=re8.exe, Ch 0000008e, errorString CTX SWITCH TIMEOUT, Info 0x27c037`

**Comment by bananananana-batman** [comment]
Having the same exact problem, tried 20+ different proton versions, every time it freezes at the same place when you walk out of stairs in the first building.
OS: Manjaro Linux x86_64 6.1.1-1-MANJARO
GPU: NVIDIA GeForce RTX 3070 
CPU: 11th Gen Intel i7-11700K
[steam-1196590.log](https://github.com/HansKristian-Work/vkd3d-proton/files/10356468/steam-1196590.log)

**Comment by mbriar** [comment]
I tried to reproduce this on AMD/RADV, but it seems to work fine there.

**Comment by HansKristian-Work** [comment]
> Basically, I noticed while playing the game that everything is fine until you get to an abandoned house outside the village. The game will hang after the furniture falls upstairs, and you go around the corner to see it.

Do you have a screenshot or something to explain exactly where things go wrong? I don't know where that is. How long does it take to get here from a new game?

**Comment by mbriar** [comment]
Takes about 5 minutes or something, according to the reddit post linked in the first post here, it's happens in the very first shack you enter after you see the mouse pop up of a closet in the basement.

**Comment by HansKristian-Work** [comment]
Ok, that should be quick to repro.

**Comment by mbriar** [comment]
FWIW, there is a bit of a stutter on AMD for me in the exact place it probably hangs on nvidia, no idea if that means anything.

**Comment by bananananana-batman** [comment]
For me its this spot, when you come up from the stairs the color of the air changes, sometimes it was glowing a bit, and immediately after this point the game is stuck
![Screenshot_20230106_130930](https://user-images.githubusercontent.com/122064566/211010570-d34193ff-f110-43c6-b713-c9a696b57ca7.png)

**Comment by Mike2003-1** [comment]
Almost identical to Banan.... sometimes i get to see around the corner through the doorway, other times i only see the wall ahead of the stairway before it freezes.

![RE8 Freeze](https://user-images.githubusercontent.com/121589492/211224239-366a5f06-f3a7-4bd4-bd1b-c59ea14b9dfa.png)

**Comment by Mike2003-1** [comment]
> Both your logs show: `vkd3d_allocate_device_memory: Memory allocation failed, falling back to system memory.` Maybe lowering your graphics settings could help?
> 
> I have the exact same issue, but for me it seems to be a driver issue. Syslog shows: `NVRM: Xid (PCI:0000:01:00): 109, pid=15138, name=re8.exe, Ch 0000008e, errorString CTX SWITCH TIMEOUT, Info 0x27c037`

My game shows in the options menu that i use 3.84 GB out of 6.97 GB available on graphics memory. If i am running out, i think it is due to some oddity / issue / bug, not that my initial settings are too high for my graphics card.

**Comment by K0bin** [comment]
> My game shows in the options menu that i use 3.84 GB out of 6.97 GB available on graphics memory.

Those numbers are just an approximation and aren't necessarily accurate.

**Comment by kodatarule** [comment]
I am not sure if it is related, but perhaps it's good to take a look at, I made a report a couple of days ago which I updated again yesterday after a lot of tinkering.
Sooooo it goes like this, basically I was playing some high demanding titles(cyberpunk, ready or not, etc) and each took my vram over it's absolutely limit and there were crashes, freezes, poor performance after some time, but when it hit me on a game I had 0 issues with a year ago... I knew something was up.
Finally after a bit of digging I was able to connect the few dots, there seems to be a huge NVIDIA driver bug which consumes as much VRAM as possible even going over the budget, I've made a few comparisons as well as provided perhaps useful information to NVIDIA dev guys about it, the reason I am mentioning this in this thread is because(Not RE: Village, but RE3 remake gave me a similar issue + on the log it says failed to allocate device memory) it's again about VRAM allocation and how it affects the game + crashes.

https://forums.developer.nvidia.com/t/vram-allocation-issues/239678

It could also affect this game it could also not, I'm not sure but something very fishy is going with latest drivers, unfortunately it didn't allow me to boot with driver 495 and 510 to test, but the problem happened somewhere around those two(515 already has the same issues as 525). Not sure what was changed, but now it goes into excessive VRAM usage and does NOT allocate.

**Comment by Mike2003-1** [comment]
@kodatarule: The game will crash in that i can not move. The atmospheric sounds continue and the window stays open, but i am unable to move. Graphics memory does not seem to max out, it actually goes towards zero. Game still takes 3.8 GB of RAM.

It looks like GE-Proton has had some issues lately, based on what they state in their latest build which is 7.47. I tried using their new 7.47, which didn't fix the issue. I also used 7.41 like @kodatarule suggests, and this also doesn't fix the issue.

**Comment by RiantAnda** [comment]
You should definitely check your syslog for anything `NVRM: Xid` related.
I'm still betting it is a nvidia bug introduced with the 5.20 or 5.25 series of drivers.

**Comment by Mike2003-1** [comment]
@RiantAnda: I'm not used to looking at this kind of info. I ran:

`journalctl -f`

... and this is the juice i collected from it:

kernel: NVRM: Xid (PCI:0000:01:00): 109, pid=9124, name=re8.exe, Ch 000000be, errorString CTX SWITCH TIMEOUT, Info 0x2c068

**Comment by RiantAnda** [comment]
@Mike2003-1: Thanks for confirming the driver issue.
You should run `/usr/bin/nvidia-bug-report.sh` after the issue happened and then e-mail the produced file with a short description to `linux-bugs@nvidia.com`. I already did that, but it may help if more people report this issue.

**Comment by MaeveFirstborn** [comment]
Hey all, wanted to chime in and say I too am experiencing this. I had a save from a Windows playthrough and I think it might be helpful to point out that the hang around the dresser is just one trigger for a seemingly much larger problem 
My save was in Manor Dimitrescu, specifically the sequence where you're going around fighting the three daughters and collecting the mask figures. Every time I got to a certain point the game just completely closed down. The dresser thing also happens to me on new saves. Lady D's dress would actually partially unload and the light fixtures above the masks would spaghettify a bit. 
RTX 3060 ti, r5 5600x, 16gb ram, Arch Linux. 

Also, I just switched to DKMS, so if someone could point me in the direction of how to downgrade from the most recent Nvidia DKMS driver to a working one, whichever one does work, that'd be greatly appreciated. I'm seeing hints that 470 works but is low performance? I have a Windows partition for emergencies (like this) so it's not the end of the world. 

Cheers everyone

**Comment by Mike2003-1** [comment]
I just want to confirm what @MaeveFirstborn is claiming. I have not seen the graphical artifacts they claim to see, but "The cabinet at the top of the stairs in the first house" is not the only place where i see my game freeze.

Before i got to this point, i had a save that started slightly after this point. I was at the first major battle, after which you are saved from Urias by someone on horseback. Randomly in this battle the game will hang in the same way, and i started over thinking there was a rare corruption in my save data. Unfortunately, as my first post indicates, i was mistaken about this.

**Comment by RiantAnda** [comment]
@MaeveFirstborn Downgrading packages in Arch is documented [here](https://wiki.archlinux.org/title/Downgrading_packages).
-You download at least [nvidia-dkms](https://archive.archlinux.org/packages/n/nvidia-dkms/) and [nvidia-utils](https://archive.archlinux.org/packages/n/nvidia-utils/), then install them with `pacman -U <package-names>`.

I can't name any known good driver version, but I would start with the 515 series.

**Comment by HansKristian-Work** [comment]
If it started happening in more recent drivers, it's worth trying `VKD3D_CONFIG=force_initial_transition %command%`. It's possible game is not transitioning depth images properly away from undefined and that caused GPU hangs in Spiderman on recent NV drivers.

**Comment by MaeveFirstborn** [comment]
That definitely sounds possible, the issues I've seen give me all the hallmarks of depth issues. It'd explain what goes on with her dress and the weird flicker of fog before the crash. I'll give it a go after work and report back!!

**Comment by MaeveFirstborn** [comment]
No dice with force_initial_transition Darn.

**Comment by RiantAnda** [comment]
I've checked out older vkd3d-proton versions and found that the issue doesn't happen with 2.5.
Seems that v2.6 introduced the hang.
@HansKristian-Work: Any ideas how we could investigate this further?

**Comment by HansKristian-Work** [comment]
Bisect?

**Comment by runar-work** [comment]
I couldn't reproduce it at the location mentioned (on the way up from the basement), but I did get it to hang randomly on the way to the house, or on loading back to the previous save point, every other attempt or so. Same as described, image freezes, but audio keeps playing.

GeForce GTX 1660 Ti
Driver version 525.47.04-234

Got the following in the kernel log:
`kernel: NVRM: Xid (PCI:0000:08:00): 109, pid=10354, name=re8.exe, Ch 000000f6, errorString CTX SWITCH TIMEOUT, Info 0x7fc07c`

**Comment by runar-work** [comment]
Oh, also, in the VKD3D log I got a bunch of memory allocation warnings before the hang.
```
01e4:warn:vkd3d_allocate_device_memory: Memory allocation failed, falling back to system memory.
01e0:warn:vkd3d_allocate_device_memory: Memory allocation failed, falling back to system memory.
01ac:warn:d3d12_device_MakeResident: iface 000000004c670030, object_count 1, objects 0000000065ecfb78 stub!
01e4:warn:vkd3d_allocate_device_memory: Memory allocation failed, falling back to system memory.
01ac:warn:d3d12_device_Evict: iface 000000004c670030, object_count 4, objects 000000002ddca960 stub!
01ac:warn:d3d12_device_EnqueueMakeResident: iface 000000004c670030, flags 0, num_objects 2, objects 00000000356fafe0, fence_to_signal 00000000006512b0, fence_value_to_signal 267 stub!
01e0:warn:vkd3d_allocate_device_memory: Memory allocation failed, falling back to system memory.
```

**Comment by l29utp0** [comment]
I can confirm this problem, works with v2.5 commit db89d40 and doesn't work with v2.5 commit c0a3fa8 and newer.

**Comment by MaeveFirstborn** [comment]
I'm new to Github, if I wanted to download and compile a specific commit, could I do that and then select that specific compatibility layer in Steam?

**Comment by MaeveFirstborn** [comment]
Oh, also, just wanted to point out, I just checked dmesg for Xid errors as referenced by a previous post and I found: 
 [+0.000003] NVRM: Xid (PCI:0000:05:00): 109, pid=127872, name=re8.exe, Ch 00000056, errorString CTX SWITCH TIMEOUT, Info 0x2c02c
Which is precisely the same error referenced in that other reply.

**Comment by HansKristian-Work** [comment]
According to @RiantAnda the issue was bisected to a particular dxil-spirv commit.

Here are three candidate vkd3d-proton commits to test to verify this. @runar-work
Remember to update submodules after checking out these commits.

- 0251b4045c2f84df4defe751b52e1475b74f3337
- 7986e241f3dd1565b9954a25ca08d3863751cc3c
- db89d403d630f229d35ef88f6be5887ccdf3b6a6

**Comment by MaeveFirstborn** [comment]
Does that mean that once VKD3D / Proton gets updated it should be fixed?

**Comment by RiantAnda** [comment]
I'm currently unable to successfully build vkd3d-proton, but the latest [proton-ge](https://github.com/GloriousEggroll/proton-ge-custom/releases) fixes the issue for me.
Many thanks @HansKristian-Work for looking into this!

**Comment by Blisto91** [comment]
> I'm currently unable to successfully build vkd3d-proton

Yes there is a regression when building with wine 8.4 that makes compilation fail. Should be fixed for next wine release.

**Comment by MaeveFirstborn** [comment]
> I'm currently unable to successfully build vkd3d-proton, but the latest [proton-ge](https://github.com/GloriousEggroll/proton-ge-custom/releases) fixes the issue for me. Many thanks @HansKristian-Work for looking into this!

I tried running it with GE 7-53 and although I could get a bit further the game crashed with the Capcom crash reporter though it didn't properly come up with an error code, idk what's going on with that

**Comment by Izowiuz** [comment]
I get the same stuff with **errorString CTX SWITCH TIMEOUT** in both Village and RE4 remake. This is with nvidia 2080 Ti on 525.89.02 What I'm currently following is this thread on nvidia forums: https://forums.developer.nvidia.com/t/multiple-cuda-rtx-vulkan-application-crashing-with-xid-13-109-errors/235459/38 as many folks had similar issues. It does sound lika a driver issue.

**Comment by MaeveFirstborn** [comment]
Have there been any updates to this?

**Comment by JIStream** [comment]
> > I'm currently unable to successfully build vkd3d-proton, but the latest [proton-ge](https://github.com/GloriousEggroll/proton-ge-custom/releases) fixes the issue for me. Many thanks @HansKristian-Work for looking into this!
> 
> I tried running it with GE 7-53 and although I could get a bit further the game crashed with the Capcom crash reporter though it didn't properly come up with an error code, idk what's going on with that

Can confirm that game randomly hangs for me on GE-55 with latest nvidia drivers. Capcom crash reported shows up just as you said.

**Comment by kleidiss** [comment]
Does this happen on RE2R as well?

I can confirm it still happens with RE Village and RE4 

RE Village tested with latest GE Wine on Lutris with VKD3d 2.8 on a RTX 3050 mobile gpu
RE4 with proton experimental

**Comment by kleidiss** [comment]
Does this issue still occur on vkd3d 2.9

**Comment by RekTek249** [comment]
> Does this issue still occur on vkd3d 2.9

Just confirmed, it still does, Xid 109 CTX SWITCH TIMEOUT. As others mentionned, this seems to be a driver issue, not related to VKD3D.

**Comment by Izowiuz** [comment]
From my **limited** testing it seems setting VKD3D_CONFIG=single_queue helps although it also impacts performance. Without it re4r freezes about ~2 minutes after loading save file and with it I was able to play for about an hour.

My assumption is that proton-ge 8.3 contains the fix for NVIDIA bug mentioned in release notes of vkd3d 2.9 which seems to be this commit: https://github.com/HansKristian-Work/vkd3d-proton/commit/2a9c5fc522ca1f7b575054575e0127efdefab0b8 as proton-ge vkd3d submodule points to this one https://github.com/HansKristian-Work/vkd3d-proton/tree/f125062ee1278ac8508ab5561e289ec4ce0f406e

I was unfortunately not able to test this in re:village.

**Comment by kleidiss** [comment]
This might have been fixed in driver 535 if you use VKd3D 2.9

**Comment by etiennep249** [comment]
I've been able to play for two hours so far without any crashes or freezes on the latest driver, kernel and vkd3d.

I was affected by the issue before, so in my case it seems to be fixed.

**Comment by MaeveFirstborn** [comment]
> I've been able to play for two hours so far without any crashes or freezes on the latest driver, kernel and vkd3d.
> 
> I was affected by the issue before, so in my case it seems to be fixed.
> 
> Edit: Nevermind, it happened again after an hour today. Xid 109.

Yeah, huge bummer. Mine still crashes shortly after the red dresser.

**Comment by Blisto91** [comment]
Could you guys give this a shot again with current master or Proton experimental? This might have been fixed by some recent work.

**Comment by runar-work** [comment]
Tested just now with 535.98 and https://github.com/HansKristian-Work/vkd3d-proton/pull/1649/commits/87cc08bf44ca4a1990620ab7921c6920011c2876. Using near max VRAM still causes a hang when I reload from a previous save, so doesn't look like anything's changed for me at least.
```
[ 8636.851764] NVRM: GPU at PCI:0000:08:00: GPU-a8fb3a3a-9dd5-b430-1b78-cb1f1ecd6079
[ 8636.851770] NVRM: Xid (PCI:0000:08:00): 109, pid=27247, name=re8.exe, Ch 000000fe, errorString CTX SWITCH TIMEOUT, Info 0x82c07f
```

**Comment by jkrhu** [comment]
Issue is still present on 535.104.05. Going up from the basement at the beginning of the game causes a hang. Tried few VRAM settings, but doesn't make a difference The game doesn't get even close to full on the 3060.

**Comment by TheMagicJesus** [comment]
I have a similar issue but it's a consistent hang in the final boss of the Shadows of Rose DLC. After the transition
 to the final phase the game hangs during the voice line. Audio continues while image. Tried in Proton GE:8-16( [steam-1196590-1.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12851159/steam-1196590-1.log )) and in Proton Experimental( [steam-1196590.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12851160/steam-1196590.log ))

`11844.914:012c:017c:err:vkd3d-proton:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
11844.914:012c:018c:err:vkd3d-proton:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
11844.917:012c:0184:err:vkd3d-proton:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
11859.704:0108:0118:fixme:oleacc:find_class_data unhandled window class: L"#32769"
11859.704:0108:0118:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
11859.704:0108:0118:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unim`

Occurs at line 34841 and line 41628  respectively.

**Comment by twiztedtbone** [comment]
Just wanted to add a report; I get the hang at the top of the stairs following the mouse/cabinet interaction in the first hut, same as: 

> For me its this spot, when you come up from the stairs the color of the air changes, sometimes it was glowing a bit, and immediately after this point the game is stuck ![Screenshot_20230106_130930](https://user-images.githubusercontent.com/122064566/211010570-d34193ff-f110-43c6-b713-c9a696b57ca7.png)

and

> Almost identical to @bananananana-batman .... sometimes i get to see around the corner through the doorway, other times i only see the wall ahead of the stairway before it freezes.
> 
> ![RE8 Freeze](https://user-images.githubusercontent.com/121589492/211224239-366a5f06-f3a7-4bd4-bd1b-c59ea14b9dfa.png)

As with others, the audio keeps going and the game doesn't outright crash, and I'm able to alt-tab to Steam to stop the game from there.

I've tried a few different Proton versions (including latest, experimental, and GE) to no avail, as well as the various launch flags mentioned in this thread. Further, I've dropped my settings to bare minimum, vsync on/off, fullscreen/windowed/borderless, basically everything I can think of. 

Two things I've not gotten around to is trying different driver versions or versions of Proton below 8.x, which I realize may be pertinent; hopefully I'll remember to update this post when I make the time to do that.

Specs:
- Arch 6.5.7
- Intel 11700F
- 3080Ti on 535.113.01

**Comment by kleidiss** [comment]
Fixed in 545?

**Comment by runar-work** [comment]
At least the Xid 109 hang I had most recently with the RTX 4070 has been fixed. It would always happen when I loaded into the second autosave point with the view of the village where I would barely have time to move before it froze. I tested with 535.113.01 again just to make sure and got an instant Xid 109. No problem with 545.23.06.

**Comment by kleidiss** [comment]
I can confirm the game no longer hard freezes

But i am getting huge surters when the game starts to hit max VRAM, which weren't there before 
Since I only have 4 GB , it isn't easy to keep VRAM below it

**Comment by TheMagicJesus** [comment]
I can also now confirm that as of Nvidia 545.29.02 the game hang no longer occurs on my end.

**Comment by HansKristian-Work** [comment]
Assuming this to be resolved now.

**Comment by MaeveFirstborn** [comment]
I can now confirm happily that, on Debian 12 with the latest Proton-GE and the official Nvidia 550 dkms install, the graphical bugs are gone and the game runs fantastic. Thank you!!
