### ISSUE TITLE
Pioneers of Pagonia Demo (2552960) Freeze when pressing anything in the HUD for placement

### ISSUE THREAD

**Issue by Somamint** [HansKristian-Work/vkd3d-proton#1725]
Like  before but still does not work:  https://github.com/HansKristian-Work/vkd3d-proton/issues/1719

The game launches, everything works. But once you try to build something the game stops to work. 

![Bildschirmfoto vom 2023-10-05 17-42-12](https://github.com/HansKristian-Work/vkd3d-proton/assets/48291814/40965727-80cd-4641-a53c-b7f770020ba9)

### Software information
[Name of the game, settings used etc.](https://store.steampowered.com/app/2155180/Pioneers_of_Pagonia/)

### System information

    GPU: RTX 2060 
    Driver: 535.113.01
    Wine version: proton-bleeding edge

### Log files
[steam-2552960.log](https://github.com/HansKristian-Work/vkd3d-proton/files/12821069/steam-2552960.log)

**Comment by doitsujin** [comment]
Can you please clarify what you mean by "stops to work" and give us the exact steps required to reproduce that? Building stuff seems to work fine here:

![Bildschirmfoto-197](https://github.com/HansKristian-Work/vkd3d-proton/assets/25567304/b54b5765-6b30-42c3-9ad3-b9100ae9653b)

**Comment by doitsujin** [comment]
What are your settings? There's a known GPU hang with upscaling enabled but that might very well be a game bug.

**Comment by Somamint** [comment]
![Bildschirmfoto vom 2023-10-05 18-40-00](https://github.com/HansKristian-Work/vkd3d-proton/assets/48291814/59425041-ec0d-4385-bb70-5592b06cda6c)

**Comment by HansKristian-Work** [comment]
The GPU hang issue is definitely an app bug.

In the UI shaders, a bindless index is passed through from VBO into pixel shader where it accesses heap out of bounds with an index of 12 million.

The VBO itself is a sysmem buffer only written by CPU. Not sure what we can do here, it's clearly a broken game.

**Comment by runar-work** [comment]
The first issue with the upscale video setting that caused GPU hangs on AMD didn't cause hangs on NV for me, but this one does give a Xid 109 on RTX 4070 with 535.43.10.

Here are breadcrumb logs: [pagonia_Xid109_logs_breadcrumbs.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/12830859/pagonia_Xid109_logs_breadcrumbs.zip)

**Comment by runar-work** [comment]
Couldn't repro this with RX 7600 and RADV 23.2.1, so seems to be NV specific for me at least.

**Comment by karzinogen** [comment]
Try the Proton Experimental with the Experimantal setting: "bleeding-edge - latest and untested dxvk, vkd3d-proton and wine changes; backup your prefixes before using".

**Comment by Somamint** [comment]
> > Try the "Proton Experimental" with the Experimantal setting: "_bleeding-edge - latest and untested dxvk, vkd3d-proton and wine changes; backup your prefixes before using_". It is a Workaround from @Dellas
> 
> Hi thx for replay. That's the version I was using. But proton experimental just received an update for me so I had hope that it'll work now. Unfortunately it still freezes after trying to build something.
> 
> I also deleted and reinstalled the game after the proton experimental update.
> 
> New Steam Log after proton Update
> 
> [steam-2552960.zip](https://github.com/HansKristian-Work/vkd3d-proton/files/12833972/steam-2552960.zip)
> 
> Screenshots:
> 
> ![freeze_after_build_click](https://user-images.githubusercontent.com/147168834/273293263-ee7f9676-7238-405c-b9aa-787fba54d282.png) ![proton_bleeding_backup_prefix](https://user-images.githubusercontent.com/147168834/273293266-5615851c-6521-4fb5-9a55-56445e5872e1.png) ![proton_experimental_update](https://user-images.githubusercontent.com/147168834/273293267-0991713e-e296-4f9a-8b5f-a98b8b89aff1.png)

Did you tried 525 Driver Version as well? I try to install this. But on POP.OS seems gone to install it.

**Comment by davidweisgerber** [comment]
I have the same problem with a RTX 4060 and 525 driver version and latest proton experimental
[steam-2155180.log.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/13686102/steam-2155180.log.gz)

**Comment by RalfKornmannEnvision** [comment]
The freeze is caused by this pixel shader. It's only used to render the helper ui during build mode (roads and buildings)

```
struct SDomainOut
{
    precise float4 Position : SV_POSITION;
    float2 GroundPosition : GROUNDPOS;
    float3 WorldPosition : WORLDPOS;
    float2 UV : UV;
    uint DataIndex : INDEX;
};

float sceneTime;

cbuffer primitiveData
{
    float4 primData[4096];
};

cbuffer linkData
{
    uint4 lData[4096];
};

static const float PI = acos(-1);

Texture2D tAllTextures[];
SamplerState StencilsSampler;

float4 ps_main(SDomainOut input) : SV_TARGET0
{
    while (true)
    {
        uint4 link = lData[input.DataIndex];
        
        uint index = link.x;
        
        switch (link.y)
        {
            case 0: // filled Circle
            {
                    float4 color = primData[index];
                    float4 data = primData[index + 1];
    
                    float distance = length(input.GroundPosition - data.xy);
    
                    if (distance <= data.z)
                    {
                        return color;
                    }
               
                    break;
                }
            
            case 1: // circle
            {
                    float4 color = primData[index];
                    float4 data = primData[index + 1];
    
                    float distance = length(input.GroundPosition - data.xy);
    
                    if (distance >= data.z && distance <= data.w)
                    {
                        return color;
                    }
               
                    break;
                }
            
            case 2: // Line
            {
                    float4 color = primData[index];
                    float4 linePos = primData[index + 1];
                    float4 data2 = primData[index + 2];
                
                    float t = dot(input.GroundPosition - linePos.xy, linePos.zw) * data2.y;
    
                    if (t == saturate(t))
                    {
                        float2 p = linePos.xy + t * linePos.zw;
    
                        float d = distance(input.GroundPosition, p);
    
                        if (d <= data2.x)
                        {
                            return color;
                        }
                    }
                
                    break;
                }
            
            case 3: // Filled Rectangle
            {
                    float4 color = primData[index];
                    float3 pos = float3(input.GroundPosition, 1);
                    float2 uv = float2(dot(pos, primData[index + 1].xyz), dot(pos, primData[index + 2].xyz));
                
                    if (all(uv == saturate(uv)))
                    {
                        return color;
                    }
                
                    break;
                }
            
            case 4: // Rectangle
            {
                    float4 color = primData[index];
                    float3 pos = float3(input.GroundPosition, 1);
                    float2 uv = float2(dot(pos, primData[index + 1].xyz), dot(pos, primData[index + 2].xyz));
                
                    if (all(uv == saturate(uv)))
                    {
                        float2 width = float2(primData[index + 1].w, primData[index + 2].w);
                    
                        if (uv.x <= width.x || uv.x >= (1.0 - width.x) ||
                            uv.y <= width.y || uv.y >= (1.0 - width.y))
                        {
                            return color;
                        }
                    }
                
                    break;
                }
            
            case 5: // Stencil
            {
                    float4 color = primData[index];
                    float3 pos = float3(input.GroundPosition, 1);
                    float2 uv = float2(dot(pos, primData[index + 1].xyz), dot(pos, primData[index + 2].xyz));
                
                    if (all(uv == saturate(uv)))
                    {
                        color *= tAllTextures[link.z].Sample(StencilsSampler, float2(uv.x, 1 - uv.y));
                    
                        if (color.w > 0)
                        {
                            return color;
                        }
                    }
                
                    break;
                }
            
            case 6: // filled Circle segment
            {
                    float4 color = primData[index];
                    float4 data = primData[index + 1];
                    float4 data2 = primData[index + 2];
    
                    float distance = length(input.GroundPosition - data.xy);
    
                    if (distance <= data.z)
                    {
                        float arc = atan2(input.GroundPosition.x - data.x, input.GroundPosition.y - data.y);
                    
                        arc = (arc + 2 * PI) % (2 * PI);
                    
                        if (data2.y > data2.x)
                        {
                            if (arc >= data2.x && arc <= data2.y)
                            {
                                return color;
                            }
                        }
                        else
                        {
                            if (arc <= data2.y || arc >= data2.x)
                            {
                                return color;
                            }
                        }
                    
                    }
               
                    break;
                }
            
            case 7: // filled Circle segment
            {
                    float4 color = primData[index];
                    float4 data = primData[index + 1];
                    float4 data2 = primData[index + 2];
    
                    float distance = length(input.GroundPosition - data.xy);
    
                    if (distance >= data.z && distance <= data.w)
                    {
                        float arc = atan2(input.GroundPosition.x - data.x, input.GroundPosition.y - data.y);
                    
                        arc = (arc + 2 * PI) % (2 * PI);
                    
                        if (data2.y > data2.x)
                        {
                            if (arc >= data2.x && arc <= data2.y)
                            {
                                return color;
                            }
                        }
                        else
                        {
                            if (arc <= data2.y || arc >= data2.x)
                            {
                                return color;
                            }
                        }
                    
                    }
               
                    break;
                }
        }
        
        
        
        if (link.w != 0)
        {
            break;
        }
        
        input.DataIndex++;
    }
    
    discard;
    
    return float4(0, 0, 0, 0);

}
```

To be exact it is this line that is causing it:

`color *= tAllTextures[link.z].Sample(StencilsSampler, float2(uv.x, 1 - uv.y));`

link.z is a valid index when this case is used. Beside replacing the sample with a load prevents the freeze:

```
uint w;
uint h;
uint l;

tAllTextures[link.z].GetDimensions(0, w, h, l);
color *= tAllTextures[link.z].Load(int3(uv.x * w, (1 - uv.y) * h, 0));
```

But as we lose the texture filter this way it's not an option. 

As it works with the exact same hardware with D3D12 on Windows I need to assume that the error is either in vkd3d itself or the Nvidia Vulkan driver. Both are outside of the things I personally can fix.

**Comment by RobertZenz** [comment]
On the NVIDIA forums [a moderator has acknowledged this problem and that they are looking into it](https://forums.developer.nvidia.com/t/multiple-cuda-rtx-vulkan-application-crashing-with-xid-13-109-errors/235459/237). However, nothing new so far, [last word is that they are investigating](https://forums.developer.nvidia.com/t/multiple-cuda-rtx-vulkan-application-crashing-with-xid-13-109-errors/235459/305). Several other games with similar(?) problems will be fixed in the next update of the NVIDIA drivers.

**Comment by trekkie3k** [comment]
I chime in because I use a AMD GPU and have the same problem now, after I was able to play the game for some time. I cannot narrow down what change let to this behaviour as I was not playing for a couple of weeks. In the meantime there were of course updates to Steam, Proton and the game itself.

System Info:
```
Linux interozitor 6.6.13+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.13-1~bpo12+1 (2024-02-15) x86_64 GNU/Linux

OpenGL renderer string: AMD Radeon RX 5500 XT (navi14, LLVM 15.0.6, DRM 3.54, 6.6.13+bpo-amd64)
```

**Comment by karzinogen** [comment]
It still works for me with Proton Experimental (GPU: Nvidia GTX 1070). I believe that all old Nvidea 10s work.

**Comment by Root-Core** [comment]
The game crashes on AMD and Nvidia now, when I click a button in the build menu.
Previously it just froze on Nvidia.

I tested it with several Proton versions.

**Comment by monarc99** [comment]
Same here: crash with Nvidia1060, if you try to select the building, you want to build. 

No Xid error in kernel log.

system:
https://paste.cachyos.org/p/98eba44

**Comment by monarc99** [comment]
Same here: crash with Nvidia1060, if you try to select the building, you want to build.

No Xid error in kernel log.

system:
https://paste.cachyos.org/p/98eba44

[steam-2155180.log.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/15052663/steam-2155180.log.gz)

**Comment by karzinogen** [comment]
In fact, I have to revise my last statement. My last error-free game was on 28.03. 
Now it is just as unplayable as yours.

**Comment by RalfKornmannEnvision** [comment]
Oh dear, oh dear

I needed to change the shader to work around a Intel ARC driver bug (on Windows). It looks like it now hits an assert in the vkd3d dxil to spirv conversion.

header->dominates(merge) && header->dominates(path)
../src-vkd3d-proton/subprojects/dxil-spirv/cfg_structurizer.cpp:4316

I will see if I can find a workaround for this issue

**Comment by esullivan-nvidia** [comment]
The issue with Pioneers of Pagonia freezing on NVIDIA GPUs is currently fixed in the Vulkan developer beta driver branch. It will also be fixed in the upcoming release branch drivers, but the developer beta is the the only public branch that has the fix for now.

**Comment by Somamint** [comment]
> The issue with Pioneers of Pagonia freezing on NVIDIA GPUs is currently fixed in the Vulkan developer beta driver branch. It will also be fixed in the upcoming release branch drivers, but the developer beta is the the only public release that has the fix for now.

can i install the beta driver already?

**Comment by esullivan-nvidia** [comment]
> Nice any idea, when it will be available ?

The beta driver is available now on this page under "Vulkan Beta Driver Downloads": https://developer.nvidia.com/vulkan-driver

**Comment by Somamint** [comment]
> > Nice any idea, when it will be available ?
> 
> The beta driver is available now on this page under "Vulkan Beta Driver Downloads": https://developer.nvidia.com/vulkan-driver

thanks what i mean, when will it like easy to install in the branch

**Comment by daugustin** [comment]
Did someone test with 555.42.02 (released yesterday)? Want to buy the game but only when it's finally fixed :D

**Comment by danieldebuhr** [comment]
@daugustin I confirm the game runs fine with the driver released yesterday. :partying_face:

**Comment by depate** [comment]
Hello!

The game still crashes on the initially mentioned condition on my AMD mobile system with several Proton versions.

`Linux workframe 6.9.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 16 Jun 2024 19:06:37 +0000 x86_64 GNU/Linux`

`OpenGL renderer string: AMD Radeon 780M (radeonsi, gfx1103_r1, LLVM 17.0.6, DRM 3.57, 6.9.5-arch1-1)`

**Comment by trekkie3k** [comment]
> The game still crashes on the initially mentioned condition on my AMD mobile system with several Proton versions.
> 
> `Linux workframe 6.9.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 16 Jun 2024 19:06:37 +0000 x86_64 GNU/Linux`
> 
> `OpenGL renderer string: AMD Radeon 780M (radeonsi, gfx1103_r1, LLVM 17.0.6, DRM 3.57, 6.9.5-arch1-1)`

I can confirm this also for AMD desktop GPUs, recently tested with a Radeon RX 7600.

**Comment by depate** [comment]
As the issue seems to be fixed with Nvidia graphics, do we need to [inform](https://github.com/freeorion/freeorion/releases/tag/v0.5.0.1) mesa (radv)/AMD developers?

**Comment by fakhraldin** [comment]
Testing RDNA 2 here: The freeze and crash still happens as soon as i click on the UI to lay paths. Hopefully not some third party ui middleware is being used but an own or open source one. SDL libraries should offer a solid base.

I remember the situation with buggy and proprietary "coherent ui" plaguing "planetary annihilation" for years on linux. The community got no access to the code in order to help resolving the issue.

If i may add, it is really awesome to see a game's original developer participating here to make things work. Highly appreciated!

**Comment by phako** [comment]
> Testing RDNA 2 here: The freeze and crash still happens as soon as i click on the UI to lay paths. Hopefully not some third party ui middleware is being used but an own or open source one. SDL libraries should offer a solid base.

This is a bug in the mesa driver and as written in https://github.com/HansKristian-Work/vkd3d-proton/issues/1725#issuecomment-2184087952 is fixed on mesa GIT. (can also confirm that it no longer crashes)

**Comment by 7vn1982** [comment]
> ~As the issue seems to be fixed with Nvidia graphics, do we need to [inform](https://github.com/freeorion/freeorion/releases/tag/v0.5.0.1) mesa (radv)/AMD developers?~
> 
> Edit: @trekkie3k I can confirm, that with the latest [mesa](https://gitlab.freedesktop.org/mesa/mesa/-/commit/51f2ed872e8491d0d4b72309d5117fe9f7f43672) commit from `main`, the game runs smoothly and does not crash with the mentioned issue. I also used bleeding-edge `proton-experimental` as [previously](https://github.com/HansKristian-Work/vkd3d-proton/issues/1725#issuecomment-1751188222) shown. I only observed two freezes, which did not affect the OS or graphics as before, within 5 minutes in an already won co-op endgame after 3h from the start. However, I couldn't make out any logs or errors on the Linux kernel side of things.
> 
> The used AUR packages for Archlinux are [1](https://aur.archlinux.org/packages/amdonly-gaming-mesa-git) & [2](https://aur.archlinux.org/packages/amdonly-gaming-vulkan-radeon-git).

Hey and thanks for your work on this problem!

I'm still getting the error with the latest Proton versions (9.0-3 RC, GE-Proton 9-10, 11 &12 and Experimental). I apologize for asking, but how do I get a Proton version with the fix mentioned above?

**Comment by Root-Core** [comment]
> I'm still getting the error with the latest Proton versions (9.0-3 RC, GE-Proton 9-10, 11 &12 and Experimental). I apologize for asking, but how do I get a Proton version with the fix mentioned above?

You need to use a current Kernel / current Mesa (on AMD) or Nvidia driver in combination with a recent Proton (GE9-12).
If you use an stale distro, this might be a pretty manual task.

**Comment by 7vn1982** [comment]
> > I'm still getting the error with the latest Proton versions (9.0-3 RC, GE-Proton 9-10, 11 &12 and Experimental). I apologize for asking, but how do I get a Proton version with the fix mentioned above?
> 
> You need to use a current Kernel / current Mesa (on AMD) or Nvidia driver in combination with a recent Proton (GE9-12). If you use an stale distro, this might be a pretty manual task.

Thanks for your Answer. I guess its good to mention that i use a Steam Deck, so my Linux Knowledge is rare and my ability to customize the system as well.
