### ISSUE TITLE
Eve Online Freezes

### ISSUE THREAD

**Issue by november781** [HansKristian-Work/vkd3d-proton#1825]
Eve Online will lock up and become unresponsive after a while. During gamepley the following errors will appear in the log files
```
68363.086:05dc:07dc:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Pipeline cache marked dirty. Flush is scheduled.
68365.168:05dc:07dc:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Flushing disk cache (wakeup counter since last flush = 22). It seems like application has stopped creating new PSOs for the time being.
68365.273:05dc:07dc:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Pipeline cache marked dirty. Flush is scheduled.
68366.284:05dc:07dc:info:vkd3d-proton:vkd3d_pipeline_library_disk_thread_main: Flushing disk cache (wakeup counter since last flush = 5). It seems like application has stopped creating new PSOs for the time being.
```
and
`68266.628:05dc:05e0:fixme:vkd3d-proton:shader_sm4_read_shader_data: Unexpected immediate constant buffer size 10096.`

### Software information
Eve Online, installed via Lutris using the community script. Near full graphical settings. Attached is my lutris config file. Converted to TXT to make github like it.
[eve-online-dec-2023-launcher-1704647020.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/13855183/eve-online-dec-2023-launcher-1704647020.txt)

### System information
- GPU: RTX 3070TI
- Driver: Nvidia Proprietary 535.146.02
- Wine version: wine-GE-8-25-x86_64
- VKD3D-Proton version: v2.11.1

### Log files
[Eve Online Logs.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/13855171/Eve.Online.Logs.txt)

**Comment by HansKristian-Work** [comment]
That shader issue should be fixed now on master. Please let us know if it works now.

**Comment by november781** [comment]
I'm still seeing the pipline cache errors and crashes when using commit 32ff676 as shipped with proton-GE-8-30. Also seeing the cache errors on proton experimental but I don't know what version of vkd3d-proton it uses if at all.

**Comment by november781** [comment]
[steam-0.log](https://github.com/HansKristian-Work/vkd3d-proton/files/14106900/steam-0.log)

Adding Log file from running with Proton-GE-30 until the game locked up and I had to kill it with sigterm

**Comment by november781** [comment]
This is probably an NVIDIA specific issue. I have recently picked up a 7800XT and VKD3D works fine in eve online with that. Unsure if its an nvidia driver issue or still a vkd3d issue

**Comment by Blisto91** [comment]
Is it specific areas you fly around in or is it a bit random to hit?

**Comment by november781** [comment]
> Is it specific areas you fly around in or is it a bit random to hit?

I have no way to further test this at the moment since I swapped to an AMD card but when I was dealing with this it was happening in Thera, Turnur, random Galente space and a few other spots

**Comment by Blisto91** [comment]
Haven't been able to reproduce a crash yet.
Tested with a 4080 on 550.40.07 drivers via Proton Experimental Bleeding Edge.

But attaching a shader for the devs to look at later
```
12124.138:06e0:06e4:err:vkd3d-proton:vkd3d_create_compute_pipeline: Failed to create Vulkan compute pipeline, hr 0.12124.138:06e0:06e4:err:vkd3d-proton:vkd3d_create_compute_pipeline:   Root signature: b9c1e39373a7d31f
12124.138:06e0:06e4:err:vkd3d-proton:vkd3d_create_compute_pipeline:   Shader: d9608c4a39a94fb6.
12124.138:06e0:06e4:fixme:vkd3d-proton:hresult_from_vk_result: Unhandled VkResult -13.
```
[eve-shader.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/14301991/eve-shader.tar.gz)

**Comment by HansKristian-Work** [comment]
The .spv looks perfectly valid to me, and creating a FOZ out of it replays just fine on NV and AMD, so not sure what can be done here.

**Comment by HansKristian-Work** [comment]
Most likely this was a compiler bug on 535 or something, and this is not actionable if Blisto cannot reproduce it, so closing.
