### ISSUE TITLE
Final Fantasy XVI performance & vertex explosion issues [AMD][RADV]

### ISSUE THREAD

**Issue by DistantThunder** [HansKristian-Work/vkd3d-proton#2131]
# Final Fantasy XVI performance & vertex explosion issues [AMD][RADV]

### Software information
* Final Fantasy XVI
* High/Medium mix (Dynamic Resolution enabled / Intel XESS or FSR3)
* Framegen disabled

### System information

- Operating System: Arch Linux 
- KDE Plasma Version: 6.1.4
- Kernel Version: 6.10.9-zen1-1-zen (64-bit)
- Graphics Platform: Wayland
- Processors: 16 × AMD Ryzen 7 5800X 8-Core Processor
- Memory: 62.7 Gio of RAM
- Graphics Processor: AMD Radeon RX 7900 XTX
- Mesa 24.2.2-arch1.1
- Proton Experimental - experimental-9.0-20240918

### Problem description
* The framerate appears to be particularly inconsistent trough Proton, compared to Windows (even if the game isn't perfect there), there's a heavy amount of stutter in many areas (can provide saves if necessary).
* Sometimes, some black artifact spreads over the scene:
![image](https://github.com/user-attachments/assets/f9b19e4e-9ef0-4a11-9212-d72b7e32b881)
* GFXRecon capture attempts ends up in OoM

### Log files
Please attach Proton or Wine logs as a text file:
- VKD3D debug+Proton Log: 
[ffxvi_vkd3d_debug.log.tar.gz](https://github.com/user-attachments/files/17100089/ffxvi_vkd3d_debug.log.tar.gz)

**Comment by runar-work** [comment]
Does the glitch appear often? It looks similar to the one reported in this Mesa issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/11550. If it's the same one, it should be fixed if you try with mesa-git.

**Comment by DistantThunder** [comment]
> Does the glitch appear often? It looks similar to the one reported in this Mesa issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/11550. If it's the same one, it should be fixed if you try with mesa-git.

Depends really, some sessions it is, some others it's nigh non-existent, I'll wait for a release upstream to cover this since it may not be VKD3D's faulting here.

Performance problems remain pregnant though, even though I've taken notice of : 
* https://gitlab.freedesktop.org/drm/amd/-/issues/3618

But the problems persist even beyond the fixes present of that thread.

**Comment by Blisto91** [comment]
@DistantThunder Do we know the status of this today?
