### ISSUE TITLE
CP77 GPU hang when entering inventory screen

### ISSUE THREAD

**Issue by HansKristian-Work** [HansKristian-Work/vkd3d-proton#607]
Observed a 100% GPU hang on RX 6800.

- Reproduces on v2.1, v2.2 and master, cannot be a vkd3d-proton regression. Tested on Mesa 11010b932b268c8dba2916f2f8196f09e336c42b.
- Unknown if it hangs reliably on NV.
- No obvious hang cause based on log.

**Comment by HansKristian-Work** [comment]
Doesn't hang for me on RTX 3070, a likely RADV issue.

**Comment by WinterSnowfall** [comment]
I haven't had any such issues on Nvidia either and have been playing the game a lot lately.

**Comment by smissaertj** [comment]
Since patch 1.2, every time I access the Inventory the game crashes. This happens also when starting a new game once I choose a life path and when accessing Character > Stats. Other than this the game runs fine.

The error can be seen in the system journal:
https://gist.github.com/smissaertj/c895e0c00945348ba3f5eb453950f5b6

[Steam System Information](https://gist.github.com/smissaertj/bdbe2bbeaf53b276d8251f22edbca00f)

**Comment by kakra** [comment]
For me it's fixed by game patch 1.21, I no longer see any issue, the game hasn't crashed or locked up for hours. Using NIVIDIA 450.55 branch (unchanged between 1.2 and 1.21). So it's probably a memory management issue because patch 1.21 - among others - improved memory management. But there may be a way to work around it from vkd3d because not all graphics drivers were affected in the first place, and as @WinterSnowfall reports, there was no issue there on NVIDIA drivers either.

**Comment by HansKristian-Work** [comment]
Can't seem to repro it either on 1.21.

**Comment by smissaertj** [comment]
I'm still seeing the issue. But then again, I'm using an AMD GPU :man_shrugging: .

**Comment by kakra** [comment]
Is it really a GPU hang? I can still make the game freeze by using a motorcycle to rush through the city: It seems to load assets fast enough that the game engine trips over itself and locks up, but no sign of a GPU crash (which would be logged to `dmesg` with NVIDIA drivers).

**Comment by kakra** [comment]
> I'm still seeing the issue. But then again, I'm using an AMD GPU  .

It looks like it became more unstable again with vkd3d 2.3 (NVIDIA). While I could run the game just fine for hours with vkd3d 2.2, it seems the game freezes every now and then with vkd3d 2.3 - without GPU exceptions, tho. So this is probably one more memory management issue within REDengine (or vkd3d for that matter) which usually make the game freeze. If I lower the resolution, the freezes are less likely to happen. Not sure what to make from this observation: Does it generate less memory pressure then? Is it a timing issue due to better performance with lower resolutions? I'm using the dynamic resolution feature targeted for 45 fps (1440p 50%-100%), so it often runs at 720p only in more complex scenes.

For me, freezes do not again as often in the inventory screen anymore but more likely when opening the map, or cruising the city with a car or motorcycle, in the motorcycle case, it is much more likely to freeze.

There's another [ongoing issue](https://github.com/ValveSoftware/steam-for-linux/issues/7630) which may play into this: The game may simply freeze when the Steam process dies in the background. But I didn't verify that yet. Most other games a tried simply quit/crash to desktop when this happens.

But I'm going to pause this game for a while anyways: I finished all possible side quests before Konpeki Plaza which has the black-screen bug for me - and I don't want to finish this quest by using the scanner always-on. I'll retry with the next updates of vkd3d and/or CP77.

**Comment by smissaertj** [comment]
@kakra I do believe it's a GPU crash.
Here's what I was able to pull from `dmseg`  today when entering the Inventory screen:
https://gist.github.com/smissaertj/534c6e3bafcc05a232da9fd9376135e4

Maybe it's important to share the game doesn't actually crash, it becomes _very_ slow up to a point I need to kill all the related Steam processes.

I don't believe it's a hardware issue as other games run fine. But I do have a spare AMD 5500XT laying around somewhere, I'll plug that one in when I have time during the week. 

My current system specs can be seen here:
https://gist.github.com/smissaertj/bdbe2bbeaf53b276d8251f22edbca00f

**Comment by smissaertj** [comment]
I'm seeing something else now after the 1.22 patch:
https://gist.github.com/smissaertj/1a3d2b4a9e7e23a38871873c74e13fbe

Guess I'll just put the game away for a while.

**Comment by kakra** [comment]
If you're using Proton Experimental: vkd3d was also updated to 2.3.1 which may change the errors you're seeing.

**Comment by qsniyg** [comment]
Does https://github.com/HansKristian-Work/vkd3d-proton/commit/72d9b322b89c325520e8f3060a8b60f719c52d6e help?
