### ISSUE TITLE
Visual bugs and crashing in Far Cry 6

### ISSUE THREAD

**Issue by DoomPenguin9** [HansKristian-Work/vkd3d-proton#845]
Compiling vkd3d-proton-master is the only way to play Far Cry 6 on Linux at the moment but there are some bugs and the game is not fully playable.

The first issue is that the text in the menus does not show if you compile vkd3d-proton-master as it is, you have to add `key.u.texture.allowed_swizzle = true;` [here](https://github.com/HansKristian-Work/vkd3d-proton/blob/ab4e847e745fb9f2cd36d28f259892ab4652ece0/libs/vkd3d/resource.c#L4308) before compiling to work around it.

The second issue flickering which you can see in this video https://www.youtube.com/watch?v=0psf8wDt048&t=3s

The third, and biggest problem I've encountered is the game crashing in menus. If you open your map, the game has a very high chance of crashing the AMDGPU driver.  The same goes for interacting with quest givers, crafting benches, etc. 

PC Specs:
OS: Arch Linux
Kernel: 5.14.9-zen2-1-zen
Mesa 21.3.0-devel (git-305b170229)
CPU: Ryzen 7 5800x
GPU: RX 6700 XT

**Comment by matty-r** [comment]
I managed to compile vkd3d-proton and the game launches, but no text (even after attempting the hack).

kernel: 5.14.9-zen2-1-zen
lib32-nvidia-utils 470.74-1
nvidia-dkms 470.74-1
nvidia-settings 470.74-1
nvidia-utils 470.74-1

```
05f4:info:vkd3d_get_vk_version: vkd3d-proton - applicationVersion: 2.4.0.
05f4:info:vkd3d_instance_init: vkd3d-proton - build: 1ca9ec72849fc8b0.
...
05f4:info:vkd3d_memory_info_init_budgets: Applying resizable BAR budget to memory types: 0x400.
05f4:info:vkd3d_bindless_state_get_bindless_flags: Device does not support VK_VALVE_mutable_descriptor_type.
05f4:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 4608, may be inaccurate.
05f4:info:d3d12_device_determine_ray_tracing_tier: DXR support enabled.
05f8:fixme:d3d12_device_SetResidencyPriority: iface 0000000013750030, object_count 1, objects 0000000004d2ef40, priorities 0000000004d2ef10 stub!
05f8:fixme:d3d12_swapchain_init: Ignoring swap effect 0x4.
05f8:fixme:d3d12_swapchain_init: Ignoring buffer usage 0x60.
05f8:fixme:d3d12_swapchain_init: Ignoring swapchain flags 0x42.
...
05f8:fixme:d3d12_swapchain_CheckColorSpaceSupport: iface 0000000005520790, colour_space 0, colour_space_support 0000000004d2e700 semi-stub!
05f8:fixme:d3d12_swapchain_SetColorSpace1: iface 0000000005520790, colour_space 0 semi-stub!
05f8:fixme:d3d12_swapchain_SetHDRMetaData: iface 0000000005520790, type 0, size 0, metadata 0000000000000000 semi-stub!warn:  DXGI: MakeWindowAssociation: Ignoring flags
05f8:fixme:vkd3d_create_texture_view: Cannot handle MinResourceLOD clamp of 4.000000 correctly.
05f8:fixme:d3d12_swapchain_Present1: Ignored present parameters 0000000004d2f6f0.
...
WINE VERSION = 6.18-GE-1 (Staging)
...
05f8:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x42.
warn:  DXGI: MakeWindowAssociation: Ignoring flags
05f8:fixme:d3d12_swapchain_Present1: Ignored present parameters 0000000004d2f6f0.
05f8:fixme:d3d12_swapchain_Present1: Ignored present parameters 0000000004d2f6f0.
```

**Comment by gardotd426** [comment]
Yeah as stated it doesn't work on Nvidia.

**Comment by DoomPenguin9** [comment]
I know that a proper fix for the text issue will take a while but what about the other two issues I mentioned? If they get fixed then the game will at least be fully playable for those with AMD GPUs.

**Comment by Ross-Carran** [comment]
Same issue as above, No text, seemed to crash when trying to run the bechmark.
PC Specs:
OS: Arch Linux: EndeavourOS Linux" (64 bit)
Kernel: 5.14.12-zen1-1-zen
Video Driver: 4.6.0 NVIDIA 495.29.05
CPU: AMD Ryzen 7 5800X 8-Core Processor 
GPU: NVIDIA Corporation NVIDIA GeForce RTX 2070/PCIe/SSE
[steam-13660078484926496768.log.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/7358567/steam-13660078484926496768.log.tar.gz)

**Comment by Ross-Carran** [comment]
Tried again with lqx kernel current nvidia vulkan dev and proton experimental no crashes.
Added screen shots of what the flashes and pixel stuff looks like.

![Far Cry® 62021-10-17-16-6-44](https://user-images.githubusercontent.com/19828845/137609543-8a844df0-d5ae-40a2-8e77-324238377ea4.jpg)
.
![Far Cry® 62021-10-17-16-6-57](https://user-images.githubusercontent.com/19828845/137609556-6a8c2270-a6a9-4fcc-afe6-2c37e84ee4b3.jpg)
![Far Cry® 62021-10-17-16-7-8](https://user-images.githubusercontent.com/19828845/137609567-e58ff593-e528-4adc-b617-f32421b72648.jpg)

[proton-experimental-log.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/7358637/proton-experimental-log.tar.gz)

**Comment by DoomPenguin9** [comment]
The game straight up crashes if you try to start a new game, load a game, or start the benchmark. You also can't access the the video menu(you can click on it but nothing happens). I think this started after the most recent patch.

**Comment by alex9k1** [comment]
> The game straight up crashes if you try to start a new game, load a game, or start the benchmark. You also can't access the the video menu(you can click on it but nothing happens). I think this started after the most recent patch.

Which version? On the top left in the ingame menu it says 1.1.1 for me and it's still working... well, besides the texture issues and bad performance.

**Comment by DoomPenguin9** [comment]
> > The game straight up crashes if you try to start a new game, load a game, or start the benchmark. You also can't access the the video menu(you can click on it but nothing happens). I think this started after the most recent patch.
> 
> Which version? On the top left in the ingame menu it says 1.1.1 for me and it's still working... well, besides the texture issues and bad performance.

Version 1.1.1

**Comment by K0bin** [comment]
The Vulkan spec version is completely irrelevant.

**Comment by idrisFoughali** [comment]
Same crashing behavior for me as well, 

Running on RTX 3080 
Distro: Arch-linux
Tried on bot wine wine-ge 6.18 and 6.20
Tried vkd3d-proton with and without the "hack".

So far, the text output is still not working, as for the game, it flickers.

**Comment by lunacorn** [comment]
the inventory bug is very similar to the Cyberpunk2077 inventory bug.  at main menu turn down shadows to low, and volumetric fog as well... enjoy.  (tested enough to feel confident, yet unsure what about these two settings is angering vkd3d)

**Comment by DoomPenguin9** [comment]
> the inventory,map bug is very similar to the Cyberpunk2077 inventory bug. at main menu turn down shadows to low, and volumetric fog as well... enjoy. (tested enough to feel confident, yet unsure what about these two settings is angering vkd3d)
> 
> future updates did relieve cp2077 of this issue yet it was dev updates not vulkan/mesa

I can't even get FC6 to launch properly anymore. It either doesn't launch at all(with latest tkg) or I get the splash screen an it just hangs until I use xkill to kill it. The only wine version I can get the game to launch with is 6.17-tkg but if I try to load a game or start a new game, it just crashes and I can't even click on half the options in the menu, like the video setting for example. What wine version are you using to get it to run?

**Comment by DoomPenguin9** [comment]
> Yeah I couldn't get the game to launch with @DadSchoorse's code at first (same behavior as @DoomPenguin9, but I did get it launched eventually). Same text issues.

How did you get it to run? I can only run the game with wine tkg 6.17 but it's buggy with it and crashes when I try to load a game or start a new one. Oh, and I also can't click on half the settings in the menu for some reason. With wine versions other than 6.17-tkg the game just hangs on the splash screen.

**Comment by alex9k1** [comment]
> > Yeah I couldn't get the game to launch with @DadSchoorse's code at first (same behavior as @DoomPenguin9, but I did get it launched eventually). Same text issues.
> 
> How did you get it to run? I can only run the game with wine tkg 6.17 but it's buggy with it and crashes when I try to load a game or start a new one. Oh, and I also can't click on half the settings in the menu for some reason. With wine versions other than 6.17-tkg the game just hangs on the splash screen.

Last time I tried I was using the lutris-ge-6.20 build of wine and built vkd3d-proton with `key.u.texture.allowed_swizzle = true`. Had some flickering in the benchmark, but at least the first few minutes of the game seemed to work just fine. Settings all worked too, as far as I could tell.

**Comment by gardotd426** [comment]
@alex9k1 are you on AMD or Nvidia? I'm just trying to see if the "there's no text visible on Nvidia" situation has changed. Last I checked it was the same (though I have gotten it to launch with later than 6.17 I believe).

**Comment by K0bin** [comment]
> I'm just trying to see if the "there's no text visible on Nvidia" situation has changed

It has not changed.

**Comment by gardotd426** [comment]
I figured not. Am I correct in recalling that it will likely require a new Vulkan extension?

**Comment by alex9k1** [comment]
> @alex9k1 are you on AMD or Nvidia? I'm just trying to see if the "there's no text visible on Nvidia" situation has changed. Last I checked it was the same (though I have gotten it to launch with later than 6.17 I believe).

AMD

**Comment by JonLit** [comment]
I can't compile the "hacked" version,
I tried the newest (3720 commits)
and the version @jas0n098 ([link to branch](https://github.com/HansKristian-Work/vkd3d-proton/commit/c3a92a0dad91c84fa749c55b673735cbbc278b81)
I get different Errors on both versions, could somebody maybe compile them and upload them to g drive or smth?

**Comment by SR-dude** [comment]
With nVidia's proprietary drivers, I see text in the main menu now.

**Comment by JonLit** [comment]
doesn't work for me anymore, with vkd3d-proton after latest commit (c0a3fa8adc589454a05ee2dd28430cae73b67890, 3743) and wine-ge-6.21-1 I just get a black screen after the warming up PSO-Cache window and after about a minute of blackscreen (Mangohud shows 0fps and inf frametime) it crashes. lutris logs show nothing...

**Comment by JonLit** [comment]
hmm, now I've tried it with Lutris-ge-6.19-1, but it still crashes after the blackscreen, although this time mangohud shows fps and frametimes for a few seconds, around 20fps, and I started lutris in a terminal to get log output, because for some reason lutris's log window was just empty: https://pastebin.com/vP810BXQ

**Comment by gardotd426** [comment]
I now have correctly rendering text (on Nvidia), but when I try to start the benchmark it hangs :(

**Comment by matty-r** [comment]
kernel: 5.14.9-zen2-1-zen
lib32-nvidia-utils 495.46-1
nvidia-dkms 495.46-1
nvidia-settings 495.46-1
nvidia-utils 495.46-1
Wine: Lutris-ge-6.21-1

When I get to the menu I see an in-game dialog - Windows version is outdated... update to v2004 or higher. In-game overlay also states - "The driver version of your enabled graphics adapter is out of date."

DXR features can't be enabled.

logs:
```
"
.
05dc:info:vkd3d_memory_info_init_budgets: Applying resizable BAR budget to memory types: 0x400.
05dc:info:vkd3d_bindless_state_get_bindless_flags: Device does not support VK_VALVE_mutable_descriptor_type.
05dc:info:d3d12_device_caps_init_shader_model: Enabling support for SM 6.6.
05dc:fixme:d3d12_device_caps_init_feature_options1: TotalLaneCount = 4608, may be inaccurate.
05dc:info:d3d12_device_determine_ray_tracing_tier: DXR support enabled.
05e0:fixme:d3d12_device_SetResidencyPriority: iface 0000000011030030, object_count 1, objects 0000000004e3ef50, priorities 0000000004e3ef20 stub!
05e0:fixme:d3d12_swapchain_init: Ignoring swap effect 0x4.
05e0:fixme:d3d12_swapchain_init: Ignoring buffer usage 0x60.
05e0:fixme:d3d12_swapchain_init: Ignoring swapchain flags 0x42.
05e0:fixme:d3d12_swapchain_CheckColorSpaceSupport: iface 00000000050a0790, colour_space 0, colour_space_support 0000000004e3e710 semi-stub!
05e0:fixme:d3d12_swapchain_SetColorSpace1: iface 00000000050a0790, colour_space 0 semi-stub!
05e0:fixme:d3d12_swapchain_SetHDRMetaData: iface 00000000050a0790, type 0, size 0, metadata 0000000000000000 semi-stub!warn:  DXGI: MakeWindowAssociation: Ignoring flags
05e0:fixme:d3d12_swapchain_Present1: Ignored present parameters 0000000004e3f700.
05e0:fixme:d3d12_swapchain_resize_buffers: Ignoring flags 0x42.
warn:  DXGI: MakeWindowAssociation: Ignoring flags
05e0:fixme:d3d12_swapchain_Present1: Ignored present parameters 0000000004e3f700.
05e0:fixme:d3d12_swapchain_Present1: Ignored present parameters 0000000004e3f700.
05e0:fixme:d3d12_swapchain_Present1: Ignored present parameters 0000000004e3f700.
05e0:fixme:d3d12_swapchain_Present1: Ignored present parameters 0000000004e3f700.
05e0:fixme:d3d12_swapchain_Present1: Ignored present parameters 0000000004e3f700.
0af0:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000428f700.
05e0:fixme:d3d12_swapchain_Present1: Ignored present parameters 0000000004e3f700.
[1220/070016.957:INFO:CONSOLE(1)] "Clientside treating path /en-au/game/far-cry/far-cry-6", source: https://static-dm.akamaized.net/global-navigation-prod/prod/1/global-navigation.js (1)
05e0:fixme:d3d12_swapchain_Present1: Ignored present parameters 0000000004e3f700.
05e0:fixme:d3d12_swapchain_Present1: Ignored present parameters 0000000004e3f700.
05e0:fixme:d3d12_swapchain_Present1: Ignored present parameters 0000000004e3f700.
05e0:fixme:d3d12_swapchain_Present1: Ignored present parameters 0000000004e3f700.
0af0:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000428f700.
0af0:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000428f700.
[1220/070035.686:WARNING:cert_verify_proc_win.cc(105)] Unknown error -2146762482 mapped to net::ERR_FAILED
0af0:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000428f700.
0b60:err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
0b48:err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
0b60:err:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
0b48:err:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
0b5c:err:vkd3d_wait_for_gpu_timeline_semaphore: Failed to wait for Vulkan timeline semaphore, vr -4.
0b44:err:vkd3d_wait_for_gpu_timeline_semaphore: Failed to wait for Vulkan timeline semaphore, vr -4.
0b44:err:vkd3d_wait_for_gpu_timeline_semaphore: Failed to wait for Vulkan timeline semaphore, vr -4.
.
.
.
.
"
```

This is basically just repeated until I kill the game:
`0b44:err:vkd3d_wait_for_gpu_timeline_semaphore: Failed to wait for Vulkan timeline semaphore, vr -4.`

**Comment by gardotd426** [comment]
I actually can enable all DXR affects. I don't know if you meant they were grayed out for you or what, but I was able to turn both reflections and shadows (or lighting, whichever the other one is) on. I turned them off to try and run the benchmark, but it crashes as always before the benchmark loads. 

From the moment the game launches, I get the same spam:

```
00.
0618:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000539f700.
0618:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000539f700.
0618:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000539f700.
0618:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000539f700.
0618:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000539f700.
0618:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000539f700.
0618:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000539f700.
0618:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000539f700.
0618:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000539f700.
0618:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000539f700.
0618:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000539f700.
0618:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000539f700.
```

But when it freezes at the benchmark loading screen, I don't get the semaphore lines, I get:

```
068c:err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
0674:err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
068c:err:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
0674:err:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
```

And that's it, until I'm able to alt-tab out and kill the game (I should clarify here, the game doesn't *crash* at the benchmark loading screen, the little spinny thing spins while it's loading and then it freezes and hangs until I alt-tab and kill it). 

But yeah, text works, and I can enable DXR.

**Comment by matty-r** [comment]
Yea the DXR options were greyed out in the menus. I get the same crash behaviour - appears to be loading then freezes.

**Comment by gardotd426** [comment]
My `VKD3D_CONFIG=` just consists of `dxr11` and nothing else, but I also have DXVK-NVAPI installed and enabled. But yeah they're totally not grayed out for me. But obviously having the game not hang instantly even without ray tracing is more of a priority than whether DXR is enable-able or not.

**Comment by matty-r** [comment]
Exactly - I could look into it but it's a bit pointless at this stage

**Comment by Ross-Carran** [comment]
Tried again with Proton experimental bleeding edge, text shows, crashes like everyone elses if you try to benchmark or play the game.
With "PROTON_ENABLE_NVAPI": "1", flagged in user_settings.py The Uplay launcher works but when launching the game itself it doesnt seem to be able to create the game window.

Will post both logs.
[steam-13947753599116247040-nvapi-enabled.log.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/7763994/steam-13947753599116247040-nvapi-enabled.log.tar.gz)
[steam-13947753599116247040-without-nvapi-toggled.log.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/7763997/steam-13947753599116247040-without-nvapi-toggled.log.tar.gz)

**Comment by gardotd426** [comment]
@Ross-Carran what do you mean you tried with Proton Experimental Bleeding Edge? You used some third-party tool that tries to let users run Proton outside of Steam, or you added FC6 to Steam as a non-Steam game??

Proton isn't meant to be used in this way, and you don't really have any reason to do it. Ubisoft Connect works just fine in Lutris, and you can use the latest vkd3d-proton and dxvk builds there as well.

**Comment by Ross-Carran** [comment]
no I manually set up a proper prefix to use proton.
Using STEAM_COMPAT_CLIENT_INSTALL_PATH = "path to your steam" usually $HOME/.steam/syeam
and STEAM_COMPAT_DATA_PATH = "path to your defined prefix"  $HOME/{whatever tickles your bubble}
then run the game executable with $HOME/.steam/steam/steamapps/common/Proton - Experimental/proton" run [windows executable to run]
No dodgy third party tools used, also user_settings.sample.py is in your proton directory you just rename it and edit it and the options are applied to all games.

**Comment by DoomPenguin9** [comment]
I encountered a new issue. Here are some screenshots of it:
![2022-01-02_21-22_1](https://user-images.githubusercontent.com/85156713/147936702-b767ef83-ab4e-45be-abe7-9cebd5a60c61.png)
![2022-01-02_21-23](https://user-images.githubusercontent.com/85156713/147936737-e99ca929-9962-409d-ad47-c380ce3279ee.png)

**Comment by howels** [comment]
Ryzen 3900X Nvidia 2080ti
Ubuntu 20.04 with HWE - Kernel 5.11.0
Nvidia driver 470.86
VK3D v2.5L-db89d40
DXVK NVAPI v0.5-e23d450

With Lutris and Wine 7.0 RC3 GE and v2.5L-db89d40 I can get into the game but the first time anything explodes the game will freeze.

**Comment by DoomPenguin9** [comment]
I think all the issues I listen in my original post are fixed now, on AMD GPUs at least. Can someone with an Nvidia card confirm everything is working fine?

**Comment by gardotd426** [comment]
> I think all the issues I listed in my original post are fixed now, on AMD GPUs at least. Can someone with an Nvidia card confirm if everything is working fine?

Definitely still not working fine. Just compiled latest vkd3d-proton, dxvk, and dxvk-nvapi, and it still freezes at the loading screen when trying to start a game or benchmark.

The terminal output has 108,797 lines of

```
05e4:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000538f700.
```

But during the actual freeze, like at the moment it freezes, there's this:

```
0660:err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
0648:err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
0660:err:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
0648:err:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
```

**Comment by dominikzogg** [comment]
I get the following which makes the xserver unsuable without a restart.

```
0418:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000404f700.
amdgpu: The CS has been cancelled because the context is lost.
048c:err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
amdgpu: The CS has been cancelled because the context is lost.
0474:err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
amdgpu: The CS has been cancelled because the context is lost.
0484:err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
0418:fixme:d3d12_swapchain_Present1: Ignored present parameters 000000000404f700.
X connection to :0 broken (explicit kill or server shutdown).
X connection to :0 broken (explicit kill or server shutdown).
X connection to :0 broken (explicit kill or server shutdown).
wine: Unhandled page fault on read access to FFFFFFFFFFFFFFFF at address 00007FA14243644C (thread 00bc), starting debugger...
free(): corrupted unsorted chunks
00bc:err:seh:call_stack_handlers invalid frame 000000000125E050 (0000000001042000-0000000001240000)
00bc:err:seh:NtRaiseException Exception frame is not in stack limits => unable to dispatch exception.
X connection to :0 broken (explicit kill or server shutdown).
X connection to :0 broken (explicit kill or server shutdown).
024c:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0079FEB4
03e4:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 008AFEB4
```

**Comment by SR-dude** [comment]
For me on a GTX 970 4GB using the 470.94 drivers, the game crashes when trying to run the built-in benchmark. I compiled the master tip.

**Comment by gardotd426** [comment]
Yeah I don't get an X crash, once I get to the `failed to submit queue` part and it freezes I have to keep hitting alt-tab (it doesn't work at first) until I can tab out and kill it the process. But yeah I get the same `0484:err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.` errors. I'm on Nvidia though, in my experience it handles freezes like this better than AMD, I've been in similar situations back when I had an AMD GPU and it would lock up the system and I'd have to reboot.

**Comment by JooJooBee666** [comment]
With the latest git build of vkd3d, I no longer have any issues at all with AMD here.  I can go in to the maps/menus without risk of hanging the GPU (which was unrecoverable without a reboot before).

Dual Intel Xeon E5-2687W v2 @ 3.40GHz,
128GB RAM
AMD RTX 6700 XT
Kubuntu 21.10
Mesa 22.0.0-devel (git-2002e87 2022-01-24)
VKD3D built off of [91976b2eddb3aca4c1323529af2c38aab223769d](https://github.com/HansKristian-Work/vkd3d-proton/commit/91976b2eddb3aca4c1323529af2c38aab223769d)

It was nice to finally play this game.  I played for 4 hours straight last night, no problem.  Prior to this, I could play for just a few minutes before I had to go to the map or pull up a workbench menu at which point there was a 70% chance of GPU hang.  I didn't notice any visual glitches either.

**Comment by kattjevfel** [comment]
I can't for the life of me get this game actually launch anymore, it used to launch 4 months ago, but since I'm on AMD it would just crash my whole computer as soon as a workbench was opened, which stopped me dead in my tracks in the tutorial.

Now it just crashes at a black screen when I go to launch it, tried latest vkd3d-proton git master, tried a bunch of different wine builds with and without fshack etc.. I guess next step is starting over and re-downloading this absolute behemoth of a game.

Arch Linux, Linux 5.16.5-zen, mesa 21.3.5

**Comment by Ross-Carran** [comment]
Tried the game again, it now works with the nvidia drivers, will list wine, Dxvk and Vkd3d below.

System: Pop_OS 21.10
              R7 5800X CPU
              RTX 2070 8gb Normal

Nvidia Driver:  470.86
Wine: Wine-Ge - 7.1-GE-1
Dxvk: master - commit 2673d7427037fdd6aab9121d04a3a064759fcaa3
Vkd3d: master - commit 33f17cc74d341a22ddba701a68761e710e328777
DXVK-NVAPI: lutris - v0.5-e23d450

Hoping some other nvidia users can give it a go, to see if it works for them as well

**Comment by gardotd426** [comment]
I 100% can still **NOT** confirm @Ross-Carran's results. Nothing has changed whatsover. Trying to either run a benchmark or start a game freezes at the loading screen (With the little spinny thing at the bottom right) with the exact same terminal output as before. I'm using literally everything the same as Ross, other than GPU (RTX 3090), CPU (5900X), and driver version (510.47.03). Using lutris-ge 7.1-1, using the literal exact same commits of DXVK, VKD3D-Proton, and DXVK-NVAPI, everything. 

The game had an update when I launched Ubisoft Connect, so I thought maybe that's what was going to fix the issues, but sure enough no, same exact crash (or rather freeze) as before. 

I left it sat for like 5 minutes just to see if it would eventually continue loading (I've seen it happen before), but no, it was frozen. 

I guess I can boot into a secondary install and try with 470.86, but I highly, *highly* doubt that is the issue, considering it never worked on 470.86 before.

**Comment by aHcVolle** [comment]
I just tried it with success with the following settings:

lutris: farcry6 installer https://lutris.net/games/far-cry-6/
wine: lutris-ge-7.1.1 (prebuilt from GE github)
DXVK: v1.9.4L-2 (was preset by the installer)
VKD3D: vkd3d-proton-git from aur (version was v2.1.r38.g2560c768-1)
DXVK NVAPI: v0.5-e23d450 (was preset by the installer/ is default)
nvidia-dkms: 510.47.03-3
kernel: linux-zen 5.16.5.zen1-1
GPU: GTX0180
CPU: i7-4820

I could load my savegame and the game was playable (just tried to launch it, didn't check if it was running stable,...)

**Comment by gardotd426** [comment]
Yeah I have no idea what's going on, I've tried it with both the generic Ubisoft Connect installer and with deleting the prefix and trying again with the lutris.net/games/far-cry-6 installer. With and without texture packs. 

The first time I tried with the actual FC6 Lutris install script and tried to run the benchmark, it actually got past the little spinny loading thing, and then froze (I could hear the benchmark sounds running, but the screen was frozen black). 

But after that, I'm right back to where I was: 
![Screenshot_20220206_091503](https://user-images.githubusercontent.com/54234607/152685512-4c774d31-78c1-406b-a026-57c91c5f2a4c.png)

It freezes there every time. I have to alt-tab out to kill it (and I have to alt-tab like, several times before it actually starts switching windows, it doesn't freeze the whole system but it kind of does, it's hard to explain. I'll try to record it with OBS or something later). 

Anyway, as soon as the freeze hits, I still get the same exact terminal output as always:

```
06c4:err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
06ac:err:d3d12_command_queue_execute: Failed to submit queue(s), vr -4.
06c4:err:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
06ac:err:d3d12_command_queue_signal: Failed to submit signal operation, vr -4.
```

Every time. Prior to the freeze, I get hundreds (or thousands) of lines of:

```
0650:fixme:d3d12_swapchain_Present1: Ignored present parameters 00000000052ff6b0.
0650:fixme:d3d12_swapchain_Present1: Ignored present parameters 00000000052ff6b0.
0650:fixme:d3d12_swapchain_Present1: Ignored present parameters 00000000052ff6b0.
0650:fixme:d3d12_swapchain_Present1: Ignored present parameters 00000000052ff6b0.
```

But I watch on my second monitor with the terminal open and the second the freeze happens, it's those 2 `Failed to submit queue(s), vr -4` lines and the 2 `failed to submit signal operation, vr -4` lines. 

So far today I've tried with lutris-ge-7.1-1, lutris-6.21 (the default with the far cry 6 install script), and my own wine-tkg-git 7.0 and 7.1 (with and without fshack built in).

**Comment by Ross-Carran** [comment]
You can try giving these a go.
Built against.
Meson: 0.56.2
glslang: 11.1.0
MingW-w64: 8.0.0 target compiler version -> 10.3.0
[vkd3d-proton-master.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/8010830/vkd3d-proton-master.tar.gz)
[dxvk-master.tar.gz](https://github.com/HansKristian-Work/vkd3d-proton/files/8010831/dxvk-master.tar.gz)

If your using lutris, copy the folders into their respective directories.
$HOME/.local/share/lutris/runtime/dxvk
$HOME/.local/share/lutris/runtime/vkd3d
![Screenshot from 2022-02-07 07-21-09](https://user-images.githubusercontent.com/19828845/152695385-339cc2c0-4acb-4c35-8c86-5cb9ad143f6d.png)

![Screenshot from 2022-02-07 07-21-17](https://user-images.githubusercontent.com/19828845/152695391-3674ea15-e645-4032-ab49-90b86be88624.png)


Then in lutris in "runner options" physically type the directories "NAME" into dxvk and vkd3d sections.
![Screenshot from 2022-02-07 07-19-23](https://user-images.githubusercontent.com/19828845/152695318-34b2d238-7ff7-4544-b6ee-a3b35b14cff3.png)

**Comment by Ross-Carran** [comment]
Crashes with Nvidia 495.46 Driver
[lutris-far-cry-6.log](https://github.com/HansKristian-Work/vkd3d-proton/files/8011184/lutris-far-cry-6.log)
![Screenshot from 2022-02-07 09-29-36](https://user-images.githubusercontent.com/19828845/152700311-1b4a29dd-f3d3-4720-9a0a-d9273aeeaf09.png)

**Comment by JonLit** [comment]
For me, the game now runs flawelessly, I had to reinstall it, and change vkd3d to the version after the latest commit (downloaded from here: [link to download page](https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/1795186075). Before that the it sometimes completely messed up my entire gui, to the point where even restarting KWin didn't do anything, but after changing vkd3d that error was gone. Although sometimes there is some flickering (VERY rarely) I consider it perfectly playable.

The benchmark also ran without any problems:
My Hardware:
i7-4790k
MSI RX 6700 XT MECH 2X OC (Mesa 22.0.0-devel (git-268fc8e5c1))

Benchmark was run in 1080p with Ultra settings, apart from raytracing(off) and motion blur (off)

avg FPS: 57
max FPS: 91
min FPS: 44
rendered Frames: 3435

Considering the rather old CPU, I'm pretty surprised how good it runs.

**Comment by gardotd426** [comment]
@Ross-Carran it's not the vkd3d-proton or DXVK versions, I already (and have for a long while) compiled the vkd3d-proton and DXVK versions I use in Lutris myself, and more importantly I also tried the exact configuration that @aHcVolle had apparent success with (only difference was the kernel). 

I have a secondary root partition that I keep other installs (either Pop OS, Ubuntu, or Manjaro) on specifically for stuff like this, I'll try launching it in Pop OS. But other than there's no reason it shouldn't work. Do either of you have set `DXVK_CONFIG_FILES`?

**Comment by Ross-Carran** [comment]
It's the Nvidia Drivers @gardotd426 at least currently from what I can tell.

Nvidia 470.103.01 and 470.86. Work for me.
Nvidia 510.47.03 and 495.47.03 crash the game.

Compile the most current Vkd3d and use one of those 470.x.x Nvidia Drivers

**Comment by gardotd426** [comment]
@Ross-Carran @aHcVolle had it working on 510.

**Comment by Ross-Carran** [comment]
I'll give it another go with 510, I always try the benchmark first, if that doesn't work I don't try to run the game in any other mode.
Don't run any special DXVK settings or anything. 

Only reason I figure it could be a driver issue is Planetary Annihilation: Titans hates those drivers as well at least on this computer.  And it's a native Linux game.

**Comment by Ross-Carran** [comment]
@aHcVolle Do you use wayland, if you do which desktop environment do you use and do you run your games with gamescope ?

**Comment by aHcVolle** [comment]
I'm using KDE plasma (latest version, not sure if its 5.23 or 5.24) with X11. No, i'm not using gamescope (never heard of it :) )

**Comment by gardotd426** [comment]
Gamescope doesn't work at all with Nvidia, last I was aware.

**Comment by Ross-Carran** [comment]
Your right, so between yesterday and today, fluffed around a bit. Managed to get a gnome 4 setup with wayland running.
Tried the game with 495 and 510 both failed, tried with 470 that failed too... switched to x11 470 495 510 failed.

Changed kernel to the most current lqx kernel 5.16.x from aur 470 worked 495 and 510 failed.
So now, im going to give the zen kernel a try and see what happens.

If it's a kernel thing, what would be different in the kernel config to get the game to work with the driver?

Will see if i can get as close to @aHcVolle s kernel setup and see if that makes the difference.

**Comment by aHcVolle** [comment]
Just had time to play the game again. i tried @Ross-Carran's vkd3d build from above with everything else as setup by the lutris script as default. the game was running perfectly for me.

**Comment by Ross-Carran** [comment]
Game runs fine until I shoot a gas cylinder, the explosion crashes the game.

Have Lutris log.
have a apitrace log from a different load, that finds exceptions on loading the PSO cache and crashes the game at load.
[farcry6-apitrace-dump.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/8064992/farcry6-apitrace-dump.txt)
[lutris-farcry6.log](https://github.com/HansKristian-Work/vkd3d-proton/files/8064993/lutris-farcry6.log)

**Comment by JonLit** [comment]
Has anyone tried RayTracing?
For me the option is just greyed out, I've tried a few different wine versions, vkd3d versions, I also tried adding the VKD3D_CONFIG=dxr11 env variable, but still isn't available...

my setup:
i5-12600k
rx6700xt
Garuda Linux KDE (Arch-based)

**Comment by Oschowa** [comment]
You need RADV_PERFTEST=rt as well, but on AMD there is almost no point in trying because driver support is still too incomplete for DXR1.1 games.

**Comment by JonLit** [comment]
> 

No, still isn't available...
I have this as prefix in Lutris config for far cry 6 `VKD3D_CONFIG=dxr11 RADV_PERFTEST=rt`

**Comment by JonLit** [comment]
> You need RADV_PERFTEST=rt as well, but on AMD there is almost no point in trying because driver support is still too incomplete for DXR1.1 games.

what would happen then? just no raytracing even though it's enabled or what do you mean it's too incomplete for DXR1.1?

**Comment by Oschowa** [comment]
Anything could happen from no option being available, crashes, broken rendering, gpu hangs. With too incomplete i mean that it's missing necessary features and has too many bugs.

**Comment by JonLit** [comment]
> 

huh okay, so the option not being available ingame could also be because of that?

**Comment by Oschowa** [comment]
Yes, but you can also try VKD3D_FEATURE_LEVEL=12_2 to maybe get the option to show up.

**Comment by JonLit** [comment]
> Yes, but you can also try VKD3D_FEATURE_LEVEL=12_2 to maybe get the option to show up.

then this happens when I start the game 
`ACO ERROR:
    In file ../mesa-22.0.1/src/amd/compiler/aco_instruction_selection.cpp:9098
    Unimplemented intrinsic instr: intrinsic rq_initialize (ssa_258, ssa_14, ssa_0, ssa_257, ssa_261, ssa_260, ssa_259, ssa_240) ()
wine: Assertion failed at address 00007FBB5FECD34C (thread 081c), starting debugger...
Unhandled exception: assertion failed in 64-bit code (0x00007fbb5fecd34c).`

**Comment by gripped** [comment]
After much messing around I got the game working with my Nvidia 2070 Super.
Arch alike Artix
Was on nvidia-dkms-510.68.02-1 which was freezing the game at the spinning gold icon as above.

Built this from AUR: https://aur.archlinux.org/packages/nvidia-vulkan

Installed:
```
sudo pacman -U nvidia-vulkan-dkms-470.62.29-2-x86_64.pkg.tar.zst nvidia-vulkan-utils-470.62.29-2-x86_64.pkg.tar.zst lib32-nvidia-vulkan-utils-470.62.29-2-x86_64.pkg.tar.zst
```
X.org
Kernel: 5.17.6-artix1-1
Wine: lutris-GE-Proton7-11-x86_64
dxvk: v1.10L
vkd3d-proton: Compiled from git master. Currently at this commit 1a773cfb713366948c0c76cada6453b2687f49cd
dxvk nvapi: v0.5.3 (does not seem to do anything i.e no DLSS in the menu)

Played just past exploding a gas canister due to the crash reports above. Did not crash.
Thanks for the contributors to the issue thread as I'd have given up otherwise.

**Comment by dataprolet** [comment]
The game launches fine, but I still have the text issue and a pink background instead of splashscreens etc.

Arch Linux
AMD RX 5700
Kernel 5.18.1-zen1-1-zen
mesa 22.1.0-1.1
vkd3d-proton-bin 2.6-1
wine-ge-custom 1:GE.Proton7.16-1

**Comment by PabloBru** [comment]
I'm not using Linux, but Windows 7 (and the d3d11/12, dxgi workaround) and I am also having experiencing crashes at random explosions. Will lurk eagerly until a solution is found and/or will gladly help if I can.

**Comment by AnniePosting** [comment]
just went back to the game to try playing with logs on and i got a very similar error to @Ross-Carran when an explosion happens. Theirs was:

0758:fixme:d3d12_swapchain_Present1: Ignored present parameters 00000000049bf6b0.

and mine was:

0668:fixme:d3d12_swapchain_Present1: Ignored present parameters 0000000004e6f840.

[lutris-farcry6.log](https://github.com/HansKristian-Work/vkd3d-proton/files/8852632/lutris-farcry6.log)

**Comment by Ross-Carran** [comment]
Haven't posted in a while, tested the game out with a tkg-wine custom build, that has winesync(Fastsync) patch applied and have the winesync kernel module installed via dkms though aur, 515.57 nvidia beta driver, dxvk-async, vkd3d-git and most recent linux-lqx kernel(5.18*).

Video card is Nvidia 2070 generic.

environment variables used were:  DXVK_ASYNC=1 WINEESYNC=0 WINEFSYNC=0 WINEFSYNC_FUTEX2=0 
WINE_FULLSCREEN_FSR=1 WINE_FULLSCREEN_FSR_STRENGTH=1

built wine with wine-tkg-git with this cfg file remove the .txt at the end.
[customization.cfg.txt](https://github.com/HansKristian-Work/vkd3d-proton/files/9039319/customization.cfg.txt)
At the very start it asked for the wine base, the one that worked was option 4 - Protonified

The game loads up and doesn't crash runs really stable.  Don't really want to work backwards to find out what changes got the game working properly. Being restricted to 5 attempts on Denuvo then being locked out for 24 hours.

**Comment by Blisto91** [comment]
@DoomPenguin9 Friendly ping (and others with that had issues). Are you still having these problems?

**Comment by Blisto91** [comment]
np. Thanks for replying

**Comment by PabloBru** [comment]
> 

Can anyone point me to the solution please?

**Comment by K0bin** [comment]
Just use a recent version of VKD3D-Proton and it should work fine.

**Comment by PabloBru** [comment]
> Just use a recent version of VKD3D-Proton and it should work fine.

Hey Kobin- can you give a noob (me) a clearer set of instructions/links please?

**Comment by K0bin** [comment]
Install vkd3d-Proton like you did before but this time do it with a more recent version.

**Comment by PabloBru** [comment]
I am using Windows 7, so I don't believe the crashes can be fixed. Thanks anyway.

**Comment by dano0b** [comment]
@PabloBru  are you aware that this github issue is about proton/vkd3d aka linux support?
